### ISSUE TITLE
I need help this error

### ISSUE THREAD

**Issue by kimsanghoon1** [ojbc/mondrian-rest#11]
```console
java.util.NoSuchElementException: Could not create a validated object, cause: enabling autocommit is not supported
```

I want to connect hive jdbc, but this error it makes me hard.

**Comment by scottcame** [comment]
This happens because Mondrian uses connection pools that attempt to set autocommit on the underlying database connections, and the hive jdbc driver (or, at least, old versions of it) don't support setting it. It looks like hive jdbc may have fixed this in a more recent version; see https://issues.apache.org/jira/browse/HIVE-11293.

In any case, closing this because there isn't anything we can do in mondrian-rest to prevent this from occurring.
